apiVersion: apps/v1
kind: Deployment
metadata:
  name: railsapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: railsapp
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
      - name: railsapp
        image: localhost:5000/my-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_ENV
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: RAILS_ENV
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: PORT
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: REDIS_URL
          - name: RABBITMQ_URL
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: RABBITMQ_URL
          - name: RABBITMQ_EXCHANGE
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: RABBITMQ_EXCHANGE
          - name: RABBITMQ_QUEUE
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: RABBITMQ_QUEUE
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: PG_HOST
          - name: PG_USERNAME
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: PG_USERNAME
          - name: PG_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: PG_PASSWORD
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: PG_DATABASE
          - name: WORKERS
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: WORKERS
          - name: SECRET_KEY_BASE
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: SECRET_KEY_BASE
          - name: ELASTICSEARCH_URL
            valueFrom:
              configMapKeyRef:
                name: railsapp-configmap
                key: ELASTICSEARCH_URL