apiVersion: v1
kind: Service
metadata:
  name: tweet-service
  namespace: twitter
  labels:
    app: tweet-service
spec:
  selector:
    app: tweet-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-service
  namespace: twitter
  labels:
    app: tweet-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tweet-service
  template:
    metadata:
      labels:
        app: tweet-service
    spec:
      containers:
      - name: tweet-service
        image: tweet-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgres.twitter.svc.cluster.local:5432/postgres?sslmode=disable"
        - name: REDIS_ADDR
          value: "redis.twitter.svc.cluster.local:6379"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq.twitter.svc.cluster.local:5672/"
        - name: ELASTICSEARCH_URL
          value: ""
        - name: JWT_SECRET
          value: "your-super-secret-jwt-key-change-in-production"
        - name: ADDR
          value: ":8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10