default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['PG_DATABASE'] %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: 'challenge_test'

production:
  <<: *default
  SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>